name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=build --parallel=3

  lint:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=lint --parallel=3

  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=test --parallel=3

