name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build - node ${{ matrix.nodeVersion }}
    runs-on: 'ubuntu-latest'
    env:
      NEXT_PUBLIC_STANZA_BROWSER_KEY: ci-only-dummy-key
    timeout-minutes: 12
    strategy:
      matrix:
        nodeVersion: [16, 18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=build --parallel=3

  lint:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=lint --parallel=3

  test:
    name: Test - node ${{ matrix.nodeVersion }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 12
    strategy:
      matrix:
        nodeVersion: [16, 18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=test --parallel=3

  coverage:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=test --parallel=3 --coverage

      - name: Install lcov
        run: sudo apt-get install lcov

      - uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: "coverage/**/lcov.info"
          minimum-coverage: 75
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

